# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "ansible-master-vm" do |vm1|
      vm1.vm.hostname = "ansible-master-vm"
      vm1.vm.box = "ubuntu/bionic64"
      vm1.vm.network "private_network", ip: "192.68.33.10"
      vm1.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
      vm1.vm.synced_folder "./data", "/vagrant_data"


      vm1.vm.provider "virtualbox" do |vb|
        vb.name = "ansible-master-vm"
        vb.gui = false
        vb.memory = "1024"
      end
    
      vm1.vm.provision "shell", inline: <<-SHELL
        apt-get update
      SHELL

      vm1.vm.provision "shell", run: "always", inline: <<-SHELL
        echo "Hello From Vagrant"
      SHELL
  end



  config.vm.define "ansible-worker-vm" do |vm2|
    vm2.vm.hostname = "ansible-worker-vm"
    vm2.vm.box = "ubuntu/bionic64"
    vm2.vm.network "private_network", ip: "192.68.33.20"
    vm2.vm.network "forwarded_port", guest: 80, host: 3008, host_ip: "127.0.0.1"
    vm2.vm.synced_folder "./data", "/vagrant_data"


    vm2.vm.provider "virtualbox" do |vb|
      vb.name = "ansible-worker-vm"
      vb.gui = false
      vb.memory = "1024"
    end
  
    vm2.vm.provision "shell", inline: <<-SHELL
      apt-get update
    SHELL

    vm2.vm.provision "shell", run: "always", inline: <<-SHELL
      echo "Hello From Vagrant"
    SHELL
  end



end